### ISSUE TITLE
Include the browser's native SubtleCrypto for every algorithm it supports

### ISSUE THREAD

**Issue by Evertt** [Daninet/hash-wasm-benchmark#10]
[[docs]](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto)
Because that would be worth knowing, right?

Currently, I'm using SubtleCrypto's sha1 digest to hash relatively small pieces of data. As in I have a plain old javascript object, which I then stringify with `JSON.stringify()` and then I hash that string. It seems to work reasonably fast, but if I knew for sure that your library is significantly faster than the native API, then I'd switch immediately. Because even though I hash small pieces of data, I do it a lot in my project, so a performance enhancement would still be welcome.

### Edit

Oh I just noticed that [you had it implemented](https://github.com/Daninet/hash-wasm-benchmark/blob/master/src/benchmark/sha1.worker.js#L30). Why did you comment it out in the end?

### Edit 2

Okay, so I just downloaded your code, and enabled the browser's native API and holy shit the results are so weird. For the 32 bytes of data, it performs quite poorly (approximately 7 MB/s vs your library's 50 MB/s). But for the 1 MB of data, the native API is crazy fast. I'm getting approximately 2 GB/s vs your library's 700 MB/s. That's crazy and makes me wonder how big my JSON objects actually are 😅.

### Edit 3

Well anyway, for anyone who is interested, these were the results on my macbook air when I re-enabled the browser's native crypto API. And to make the screenshot not too huge I'm only showing the numbers that are actually kind of interesting / relevant to see.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/1267282/192085454-623195c0-20c8-4aa7-81aa-fe424ee85774.png">

**Comment by Daninet** [comment]
Yeah, that's the reason. In my measurements the browser-native API has very different performance characteristics depending on the platform / OS / browser / CPU revision. When I use my Linux based laptop, I get totally different numbers compared to a Macbook's Apple Silicon, while hash-wasm and other libraries from NPM give much more consistent performance across different platforms. Subtle crypto also has a disadvantage of not being multithreaded, while the hash-wasm can be parallelized using Worker Threads. 
But I will consider adding a note about SubleCrypto to the readme.
